### PR TITLE
Activate python-deduckt command console

### PR DESCRIPTION
**Pull request by nilanjanray**
1.  Enable the console script from setup.py & corrected the function name as expected from console script
2.  Minor adjustment over main.py as it's seen that deduckt module have main *def* which compile the source and generates *ast* - so introduce absolute import and use the *main* function as base of the main.py
3. Currently  ``` if __name__ == '__main__':``` doesn't have used , please suggest if any more concern on it

### CODE REVIEW

**Comment by zah** [comment]
The original structure was copied from another command-line debugger for Python. My impression was that the goal of this stub module is to ensure that  `__name__ == '__main__'` doesn't hold true in `deduckt.main`, but this is just an assumption.

Have you ran into any problems prior to the change?

**Comment by nilanjanray** [comment]
@zah Yes that *python-deduckt* command was not running due to unavailability of *cli* function , actually no *def cli()* is available in the library itself. *compile* is used in *def main()* of ```deduckt.py```

**Comment by zah** [comment]
OK, merging. I assume you've tested it a bit by now and it doesn't seem to break anything.

**Comment by jacereda** [comment]
py2nim won't work with master after this change.

**Pull request merged**
